version: '3'

services:
  web:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: nome_do_banco
      MYSQL_USER: usuario_db
      MYSQL_PASSWORD: senha_db
    ports:
      - "3306:3306"
